In [72]:
import numpy as np
from numpy import loadtxt
print('import')

import


In [73]:
seq = loadtxt('input/day4', dtype=int, max_rows=1, delimiter=',')
cards = loadtxt('input/day4', dtype='str', skiprows=2, delimiter='\n')
print(seq)

[93 49 16 88  4 92 23 38 44 98 97  8  5 69 41 70 19 11 29 40 90 43 79 96
 68 10 31 35 34 32  0 67 83 33  2 76 24 87 99 77 82 66 12 15 28 59 64 95
 91 71 62 22 53 46 39 81 75 86 74 56 50 18 17 73 13 54 60 48 21 51 52 55
 85 80 30 36 47  3 26 57 84 25 63 27 37 94  7 45 58  9 78 65 72  6 14 61
 20  1 42 89]


In [74]:
cardList = []
for i in cards:
    nums = i.split(' ')
    nums = list(filter(lambda val: val != '', nums))
    nums = list(map(int, nums))
    cardList.append(nums)

In [75]:
plus = []
cardFinal = []
for i in range(0, len(cardList)):
    plus.append(cardList[i])
    if (i + 1) % 5 == 0:
        cardFinal.append(plus)
        plus = []

In [76]:
card = np.empty((len(cardFinal), 5, 5), dtype=int)
for i in range(0, len(cardFinal)):
    for j in range(0, len(cardFinal[i])):
        for k in range(0, len(cardFinal[i][j])):
            card[i, j, k] = cardFinal[i][j][k]

boolCard = np.zeros((len(cardFinal), 5, 5), dtype=int)

In [77]:
def winCheck(arr):
    win = np.ones(5, dtype=int)
    for i in range(0, 5):
        if np.array_equal(arr[i], win) or np.array_equal(arr[:, i], win):
            return True
    return False

In [78]:
def bingoNumber(bingoCard, index, bingoNum):
    for i in range(0, len(bingoCard)):
        for j in range(0, len(bingoCard[i])):
            if bingoCard[i, j] == bingoNum:
                boolCard[index, i, j] = 1

In [79]:
winningNum = -1
winBool = False
for num in seq:
    for bingoCardIndex in range(0, len(card)):
        bingoNumber(card[bingoCardIndex], bingoCardIndex, num)
        if not winCheck(boolCard[bingoCardIndex]):
            print(card[bingoCardIndex])
            print(boolCard[bingoCardIndex])
            print(bingoCardIndex)
            print(num)
            winningNum = num
            winningIndex = bingoCardIndex

print('done')

[[83 11 47 61 45]
 [30 74 73 14 66]
 [53 52 10 57 15]
 [64 50 54 28 87]
 [26 85 63 25 86]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0
93
[[72  4 62 30 49]
 [43 93 39 63 25]
 [18 70 44 77 38]
 [84  8 85  5 26]
 [54 50 40 75  2]]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
1
93
[[70 78 55 26 35]
 [75 44 80 15 34]
 [67 47 53 10 56]
 [73 46 27 38 13]
 [64 92 39 87 23]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2
93
[[24 66 11 44 51]
 [32 37 83 69 85]
 [46 59 14 99 76]
 [71 28 94 35 98]
 [16 40 74 80  6]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
3
93
[[ 1 55 42 59 70]
 [87 81 68 83 56]
 [12 21 20 49 84]
 [89 92 94  2 76]
 [ 5 17 77  3 32]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
4
93
[[66 98 10 53 78]
 [80 92 26 38 29]
 [46 34 22 51  8]
 [43 89 87 64 17]
 [63 86 84 62 15]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
5
93
[[75 65 96 19 87]
 [12 51 97