In [666]:
import numpy as np
from numpy import loadtxt
print('import')

import


In [667]:
seq = loadtxt('input/day4', dtype=int, max_rows=1, delimiter=',')
cards = loadtxt('input/day4', dtype='str', skiprows=2, delimiter='\n')
print(seq)

[93 49 16 88  4 92 23 38 44 98 97  8  5 69 41 70 19 11 29 40 90 43 79 96
 68 10 31 35 34 32  0 67 83 33  2 76 24 87 99 77 82 66 12 15 28 59 64 95
 91 71 62 22 53 46 39 81 75 86 74 56 50 18 17 73 13 54 60 48 21 51 52 55
 85 80 30 36 47  3 26 57 84 25 63 27 37 94  7 45 58  9 78 65 72  6 14 61
 20  1 42 89]


In [668]:
cardList = []
for i in cards:
    nums = i.split(' ')
    nums = list(filter(lambda val: val != '', nums))
    nums = list(map(int, nums))
    cardList.append(nums)


In [669]:
plus = []
cardFinal = []
for i in range(0, len(cardList)):
    plus.append(cardList[i])
    if (i + 1) % 5 == 0:
        cardFinal.append(plus)
        plus = []


In [670]:
card = np.empty((len(cardFinal), 5, 5), dtype=int)
for i in range(0, len(cardFinal)):
    for j in range(0, len(cardFinal[i])):
        for k in range(0, len(cardFinal[i][j])):
            card[i, j, k] = cardFinal[i][j][k]

In [671]:
boolCard = np.zeros((len(cardFinal), 5, 5), dtype=int)

In [672]:
def winCheck(arr):
    win = np.ones(5, dtype=int)
    for i in range(0, 5):
        if np.array_equal(arr[i], win) or np.array_equal(arr[:, i], win):
            return True
    return False

In [673]:
def bingoNumber(bingoCard, index, bingoNum):
    for i in range(0, len(bingoCard)):
        for j in range(0, len(bingoCard[i])):
            if bingoCard[i, j] == bingoNum:
                boolCard[index, i, j] = 1

In [674]:
winningNum = -1
winBool = False
for num in seq:
    if winBool == True:
        break
    for bingoCardIndex in range(0, len(card)):
        bingoNumber(card[bingoCardIndex], bingoCardIndex, num)
        if winCheck(boolCard[bingoCardIndex]):
            print(card[bingoCardIndex])
            print(boolCard[bingoCardIndex])
            print(bingoCardIndex)
            winningNum = num
            winningIndex = bingoCardIndex
            winBool = True

print('done')

[[91 22 89 72 82]
 [63 58 80 42 45]
 [11 40 29 41 90]
 [17 16 62 14 35]
 [23  4 65 79  0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 1 0 0 0]
 [1 1 0 0 0]]
62
done


In [675]:
def score(bingoCardIndex):
    scorelist = []
    for i in range(0, len(card[bingoCardIndex])):
        for j in range(0, len(card[bingoCardIndex, i])):
            if boolCard[bingoCardIndex, i, j] == 0:
                scorelist.append(card[bingoCardIndex, i, j])
    print(scorelist)
    return sum(scorelist) * winningNum

In [676]:
print(score(winningIndex))

[91, 22, 89, 72, 82, 63, 58, 80, 42, 45, 17, 62, 14, 35, 65, 79, 0]
82440
