In [101]:
from numpy import loadtxt
import numpy as np
print('import')

import


In [102]:
data = loadtxt('input/day5demo', dtype='str', delimiter='\n', )
print(data)

['0,9 -> 5,9' '8,0 -> 0,8' '9,4 -> 3,4' '2,2 -> 2,1' '7,0 -> 7,4'
 '6,4 -> 2,0' '0,9 -> 2,9' '3,4 -> 1,4' '0,0 -> 8,8' '5,5 -> 8,2']


In [103]:
for i in range(len(data)):
    space = str.index(data[i], ' ')
    data[i] = data[i][0:space] + ',' + data[i][str.index(data[i], ' ', space + 1) + 1:]
print(data)

['0,9,5,9' '8,0,0,8' '9,4,3,4' '2,2,2,1' '7,0,7,4' '6,4,2,0' '0,9,2,9'
 '3,4,1,4' '0,0,8,8' '5,5,8,2']


In [104]:
intData = np.ones((len(data), 4), dtype=int)
for i in range(len(data)):
    points = data[i].split(',')
    for j in range(4):
        intData[i, j] = points[j]
print(intData)

[[0 9 5 9]
 [8 0 0 8]
 [9 4 3 4]
 [2 2 2 1]
 [7 0 7 4]
 [6 4 2 0]
 [0 9 2 9]
 [3 4 1 4]
 [0 0 8 8]
 [5 5 8 2]]


In [105]:
lines = 0
def linecheck(arr):
    if arr[0] == arr[2] or arr[1] == arr[3]:
        return True

for i in range(len(intData)):
    if linecheck(intData[i]):
        lines += 1

lineData = np.ones((lines, 4), dtype=int)
lineDataIndex = 0
for i in range(len(intData)):
    if linecheck(intData[i]):
        lineData[lineDataIndex] = intData[i]
        lineDataIndex += 1
print(lineData)

[[0 9 5 9]
 [9 4 3 4]
 [2 2 2 1]
 [7 0 7 4]
 [0 9 2 9]
 [3 4 1 4]]
