In [751]:
from numpy import loadtxt
import numpy as np
print('import')

import


In [752]:
data = loadtxt('input/day5', dtype='str', delimiter='\n', )
print(data)

['593,10 -> 593,98' '777,236 -> 964,236' '650,575 -> 476,575'
 '120,612 -> 715,17' '508,707 -> 508,89' '98,834 -> 751,834'
 '623,554 -> 623,701' '929,976 -> 62,109' '368,893 -> 330,931'
 '495,335 -> 40,335' '44,704 -> 423,704' '683,711 -> 683,487'
 '26,940 -> 833,133' '961,183 -> 454,183' '301,306 -> 301,935'
 '973,822 -> 398,822' '639,911 -> 515,911' '861,180 -> 184,857'
 '31,97 -> 857,923' '966,376 -> 966,114' '881,485 -> 881,377'
 '930,98 -> 110,918' '841,889 -> 841,35' '512,261 -> 880,261'
 '48,533 -> 48,674' '207,226 -> 52,226' '823,952 -> 177,306'
 '331,566 -> 423,566' '422,418 -> 422,130' '699,517 -> 699,567'
 '757,784 -> 241,784' '508,445 -> 560,393' '866,275 -> 435,706'
 '74,41 -> 74,258' '386,369 -> 334,317' '240,94 -> 240,969'
 '851,197 -> 577,197' '28,906 -> 741,193' '286,227 -> 286,293'
 '849,800 -> 849,665' '736,307 -> 336,307' '69,701 -> 494,276'
 '421,823 -> 96,823' '121,626 -> 121,393' '318,351 -> 194,351'
 '670,671 -> 439,671' '603,914 -> 603,272' '61,507 -> 61,889'
 

In [753]:
for i in range(len(data)):
    space = str.index(data[i], ' ')
    data[i] = data[i][0:space] + ',' + data[i][str.index(data[i], ' ', space + 1) + 1:]
print(data)

['593,10,593,98' '777,236,964,236' '650,575,476,575' '120,612,715,17'
 '508,707,508,89' '98,834,751,834' '623,554,623,701' '929,976,62,109'
 '368,893,330,931' '495,335,40,335' '44,704,423,704' '683,711,683,487'
 '26,940,833,133' '961,183,454,183' '301,306,301,935' '973,822,398,822'
 '639,911,515,911' '861,180,184,857' '31,97,857,923' '966,376,966,114'
 '881,485,881,377' '930,98,110,918' '841,889,841,35' '512,261,880,261'
 '48,533,48,674' '207,226,52,226' '823,952,177,306' '331,566,423,566'
 '422,418,422,130' '699,517,699,567' '757,784,241,784' '508,445,560,393'
 '866,275,435,706' '74,41,74,258' '386,369,334,317' '240,94,240,969'
 '851,197,577,197' '28,906,741,193' '286,227,286,293' '849,800,849,665'
 '736,307,336,307' '69,701,494,276' '421,823,96,823' '121,626,121,393'
 '318,351,194,351' '670,671,439,671' '603,914,603,272' '61,507,61,889'
 '266,39,157,39' '543,664,869,664' '382,709,884,709' '499,80,548,80'
 '489,79,878,79' '695,86,644,86' '987,585,987,557' '287,67,551,67'
 '975,983,35,

In [754]:
intData = np.ones((len(data), 4), dtype=int)
for i in range(len(data)):
    points = data[i].split(',')
    for j in range(4):
        intData[i, j] = points[j]
print(intData)

[[593  10 593  98]
 [777 236 964 236]
 [650 575 476 575]
 ...
 [405 793 405 183]
 [232 704 232 389]
 [130 706 130 657]]


In [755]:
lines = 0
def linecheck(arr):
    if arr[0] == arr[2] or arr[1] == arr[3]:
        return True

for i in range(len(intData)):
    if linecheck(intData[i]):
        lines += 1

lineData = np.ones((lines, 4), dtype=int)
lineDataIndex = 0
for i in range(len(intData)):
    if linecheck(intData[i]):
        lineData[lineDataIndex] = intData[i]
        lineDataIndex += 1
print(lineData)

[[593  10 593  98]
 [777 236 964 236]
 [650 575 476 575]
 ...
 [405 793 405 183]
 [232 704 232 389]
 [130 706 130 657]]


In [756]:
def countPoints(arr):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    distance = abs((x1 - x2) + (y1 - y2))
    return distance + 1

In [757]:
totalPoints = 0
for i in lineData:
    totalPoints += countPoints(i)
print(totalPoints)

114355


In [758]:
pointsArr = np.ones((totalPoints, 2), dtype=int)
print(len(pointsArr))
print(pointsArr)

114355
[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [759]:
def points(arr, count):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    if x1 == x2:
        distance = abs(y2 - y1)
        updown = True
    else:
        distance = abs(x2 - x1)
        updown = False

    for i in range(distance + 1):
        if updown:
            if y1 > y2:
                pointsArr[count] = np.array((x1, y2 + i))
            else:
                pointsArr[count] = np.array((x1, y1 + i))
        else:
            if x1 > x2:
                pointsArr[count] = np.array((x2 + i, y1))
            else:
                pointsArr[count] = np.array((x1 + i, y1))
        count += 1
    return count

In [760]:
pointCount = 0
for i in lineData:
    pointCount = points(i, pointCount)

pointsArr

array([[593,  10],
       [593,  11],
       [593,  12],
       ...,
       [130, 704],
       [130, 705],
       [130, 706]])

In [761]:
unique, counts = np.unique(pointsArr, return_counts=True, axis=0)

result = np.column_stack((unique, counts))
result

array([[ 13, 403,   1],
       [ 14, 403,   1],
       [ 15, 403,   1],
       ...,
       [987, 583,   1],
       [987, 584,   1],
       [987, 585,   1]], dtype=int64)

In [762]:
countArr = result[:, 2]
print(np.count_nonzero(countArr > 1))

7468


Part 2

In [763]:
from math import sqrt
def countPointsDiag(arr):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    distance = abs(x1 - x2) + 1
    return int(distance)

In [764]:
totalPoints2 = 0
for i in intData:
    totalPoints2 += countPoints(i)
print(totalPoints2)

208543


In [765]:
pointsArr2 = np.ones((totalPoints2, 2), dtype=int)
print(len(pointsArr2))
print(pointsArr2)

208543
[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [766]:
def pointsDiag(arr, count):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    if (y2 - y1) / (x2 - x1) > 0:
        positive = True
    else:
        positive = False

    distance = countPointsDiag(arr)

    for i in range(distance):
        if positive:
            if y2 > y1:
                pointsArr2[count] = np.array((x1 + i, y1 + i))
            else:
                pointsArr2[count] = np.array((x2 + i, y2 + i))
        else:
            if y2 > y1:
                pointsArr2[count] = np.array((x1 - i, y1 + i))
            else:
                pointsArr2[count] = np.array((x1 + i, y1 - i))
        count += 1
    return count

In [767]:
def points2(arr, count):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    if x1 == x2:
        distance = abs(y2 - y1)
        updown = True
    else:
        distance = abs(x2 - x1)
        updown = False

    for i in range(distance + 1):
        if updown:
            if y1 > y2:
                pointsArr2[count] = np.array((x1, y2 + i))
            else:
                pointsArr2[count] = np.array((x1, y1 + i))
        else:
            if x1 > x2:
                pointsArr2[count] = np.array((x2 + i, y1))
            else:
                pointsArr2[count] = np.array((x1 + i, y1))
        count += 1
    return count

In [768]:
#pointsDiag([9, 7, 7, 9], 0)
#points2([0, 0, 0, 5], 0)
#pointsArr2

In [769]:
pointCount2 = 0
for i in intData:
    if linecheck(i):
        pointCount2 = points2(i, pointCount2)
    else:
        pointCount2 = pointsDiag(i, pointCount2)

pointsArr2

array([[593,  10],
       [593,  11],
       [593,  12],
       ...,
       [  1,   1],
       [  1,   1],
       [  1,   1]])

In [770]:
unique, counts = np.unique(pointsArr2, return_counts=True, axis=0)

result = np.column_stack((unique, counts))
result

array([[    1,     1, 14189],
       [   11,   274,     1],
       [   11,   840,     1],
       ...,
       [  988,    23,     1],
       [  989,    10,     1],
       [  989,    22,     1]], dtype=int64)

In [771]:
countArr = result[:, 2]
print(countArr > 1)

[ True False False ... False False False]


In [772]:
print(np.count_nonzero(countArr > 1) - 1)

22364
