In [839]:
from numpy import loadtxt
import numpy as np
print('import')

import


In [840]:
data = loadtxt('input/day5', dtype='str', delimiter='\n', )
data[:5]

array(['593,10 -> 593,98', '777,236 -> 964,236', '650,575 -> 476,575',
       '120,612 -> 715,17', '508,707 -> 508,89'], dtype='<U18')

In [841]:
for i in range(len(data)):
    space = str.index(data[i], ' ')
    data[i] = data[i][0:space] + ',' + data[i][str.index(data[i], ' ', space + 1) + 1:]
print(data[:5])

['593,10,593,98' '777,236,964,236' '650,575,476,575' '120,612,715,17'
 '508,707,508,89']


In [842]:
intData = np.ones((len(data), 4), dtype=int)
for i in range(len(data)):
    points = data[i].split(',')
    for j in range(4):
        intData[i, j] = points[j]
print(intData)

[[593  10 593  98]
 [777 236 964 236]
 [650 575 476 575]
 ...
 [405 793 405 183]
 [232 704 232 389]
 [130 706 130 657]]


In [843]:
lines = 0
def linecheck(arr):
    if arr[0] == arr[2] or arr[1] == arr[3]:
        return True

for i in range(len(intData)):
    if linecheck(intData[i]):
        lines += 1

lineData = np.ones((lines, 4), dtype=int)
lineDataIndex = 0
for i in range(len(intData)):
    if linecheck(intData[i]):
        lineData[lineDataIndex] = intData[i]
        lineDataIndex += 1
print(lineData)

[[593  10 593  98]
 [777 236 964 236]
 [650 575 476 575]
 ...
 [405 793 405 183]
 [232 704 232 389]
 [130 706 130 657]]


In [844]:
def countPoints(arr):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    distance = abs((x1 - x2) + (y1 - y2))
    return distance + 1

In [845]:
totalPoints = 0
for i in lineData:
    totalPoints += countPoints(i)
print(totalPoints)

114355


In [846]:
pointsArr = np.ones((totalPoints, 2), dtype=int)
print(len(pointsArr))
print(pointsArr)

114355
[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [847]:
def points(arr, count):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    if x1 == x2:
        distance = abs(y2 - y1)
        updown = True
    else:
        distance = abs(x2 - x1)
        updown = False

    for i in range(distance + 1):
        if updown:
            if y1 > y2:
                pointsArr[count] = np.array((x1, y2 + i))
            else:
                pointsArr[count] = np.array((x1, y1 + i))
        else:
            if x1 > x2:
                pointsArr[count] = np.array((x2 + i, y1))
            else:
                pointsArr[count] = np.array((x1 + i, y1))
        count += 1
    return count

In [848]:
pointCount = 0
for i in lineData:
    pointCount = points(i, pointCount)

pointsArr

array([[593,  10],
       [593,  11],
       [593,  12],
       ...,
       [130, 704],
       [130, 705],
       [130, 706]])

In [849]:
unique, counts = np.unique(pointsArr, return_counts=True, axis=0)

result = np.column_stack((unique, counts))
result

array([[ 13, 403,   1],
       [ 14, 403,   1],
       [ 15, 403,   1],
       ...,
       [987, 583,   1],
       [987, 584,   1],
       [987, 585,   1]], dtype=int64)

In [850]:
countArr = result[:, 2]
print(np.count_nonzero(countArr > 1))

7468


Part 2

In [851]:
from math import sqrt
def countPointsDiag(arr):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    distance = abs(x1 - x2) + 1
    return int(distance)

In [852]:
totalPoints2 = 0
for i in intData:
    totalPoints2 += countPoints(i)
print(totalPoints2)

208543


In [853]:
pointsArr2 = np.ones((totalPoints2, 2), dtype=int)
print(len(pointsArr2))
print(pointsArr2)

208543
[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [854]:
def pointsDiag(arr, count):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    if (y2 - y1) / (x2 - x1) > 0:
        positive = True
    else:
        positive = False

    distance = countPointsDiag(arr)

    for i in range(distance):
        if positive:
            if y2 > y1:
                pointsArr2[count] = np.array((x1 + i, y1 + i))
            else:
                pointsArr2[count] = np.array((x2 + i, y2 + i))
        else:
            if y2 > y1:
                pointsArr2[count] = np.array((x1 - i, y1 + i))
            else:
                pointsArr2[count] = np.array((x1 + i, y1 - i))
        count += 1
    return count

In [855]:
def points2(arr, count):
    x1 = arr[0]
    y1 = arr[1]
    x2 = arr[2]
    y2 = arr[3]
    if x1 == x2:
        distance = abs(y2 - y1)
        updown = True
    else:
        distance = abs(x2 - x1)
        updown = False

    for i in range(distance + 1):
        if updown:
            if y1 > y2:
                pointsArr2[count] = np.array((x1, y2 + i))
            else:
                pointsArr2[count] = np.array((x1, y1 + i))
        else:
            if x1 > x2:
                pointsArr2[count] = np.array((x2 + i, y1))
            else:
                pointsArr2[count] = np.array((x1 + i, y1))
        count += 1
    return count

In [856]:
#pointsDiag([9, 7, 7, 9], 0)
#points2([0, 0, 0, 5], 0)
#pointsArr2

In [857]:
pointCount2 = 0
for i in intData:
    if linecheck(i):
        pointCount2 = points2(i, pointCount2)
    else:
        pointCount2 = pointsDiag(i, pointCount2)

pointsArr2

array([[593,  10],
       [593,  11],
       [593,  12],
       ...,
       [  1,   1],
       [  1,   1],
       [  1,   1]])

In [858]:
unique, counts = np.unique(pointsArr2, return_counts=True, axis=0)

result = np.column_stack((unique, counts))
result

array([[    1,     1, 14189],
       [   11,   274,     1],
       [   11,   840,     1],
       ...,
       [  988,    23,     1],
       [  989,    10,     1],
       [  989,    22,     1]], dtype=int64)

In [859]:
countArr = result[:, 2]
print(countArr > 1)

[ True False False ... False False False]


In [860]:
print(np.count_nonzero(countArr > 1) - 1)

22364
